schema: omnia
context: # Describe your project here

rules:
  proposal: |
    # TODO: Add any proposal override rules here
  specs: |
    # TODO: Add any specs override rules here
  design: |
    # TODO: Add any design override rules here
  tasks: |
    # TODO: Add any tasks override rules here